version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: david664
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10

  usuarios:
    image: brayan333/usuarios:latest
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: david664
      DB_NAME: usuariosMS
    ports:
      - "3002:3002"

  productos:
    image: brayan333/productos:latest
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: david664
      DB_NAME: productosMS
    ports:
      - "3001:3001"

  garantias:
    image: brayan333/garantias:latest
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: david664
      DB_NAME: garantiasMS
    ports:
      - "3004:3004"

  envios:
    image: brayan333/envios:latest
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: david664
      DB_NAME: enviosMS
    ports:
      - "3003:3003"

volumes:
  mysql-data:
